import ora from 'ora';
import chalk from 'chalk';
import fs from 'fs-extra';
import appRootPath from 'app-root-path';
import { importer, interfaces, prismaInstance } from '../template/models';
import {
  generateModelStructures,
  getAllModelName,
  generateModelsPrismaTypes,
  getAllModelTypes,
  generateModelNameConstants,
} from '../utils/models';
import { DEFAULT_PATH, FILES_NAME, MODEL_NAME, MODEL_SCALAR_FIELDS } from '../utils/constants';
import { PrismaRepoConfig } from '../utils/interface';

const createModelStructures = async (prisma: string, settings: PrismaRepoConfig) => {
  const spinner = ora('Creating model structures..\n.').start();
  const { repositoryPath } = settings;

  const repositoryDirPath = repositoryPath
    ? `${appRootPath}/${repositoryPath}`
    : `${appRootPath}/${DEFAULT_PATH}`;

  const filePath = repositoryPath
    ? `${appRootPath}/${repositoryPath}/${FILES_NAME.MODELS}`
    : `${appRootPath}/${DEFAULT_PATH}/${FILES_NAME.MODELS}`;

  try {
    const modelNames = getAllModelName(prisma);
    const modelNameConstants = generateModelNameConstants(modelNames);
    const modelStructures = generateModelStructures(modelNames);
    const modelsTypes = getAllModelTypes(prisma, modelNames);
    const modelsPrismaTypes = generateModelsPrismaTypes(modelNames, modelsTypes);

    let models =
      '//! Do not edit this file manually, it is generate by `prisma repo generator`\n\n';

    models += `${importer.lodash}\n`;
    models += `${importer.start} `;
    models += modelNames.join(', ');
    models += ` ${importer.end}\n\n`;

    models += `${interfaces.anyRecord}\n\n`;
    models += `${interfaces.baseOption}\n\n`;
    models += `${interfaces.find}\n\n`;

    models += `${prismaInstance.prisma}\n\n`;
    models += `${prismaInstance.models}\n\n`;

    models += `${modelNameConstants}\n\n`;

    models += `${modelStructures}\n\n`;
    models += `${MODEL_NAME}\n\n`;
    models += `${MODEL_SCALAR_FIELDS}\n\n`;

    models += `${modelsPrismaTypes}\n`;

    if (!fs.existsSync(repositoryDirPath)) {
      await fs.mkdir(repositoryDirPath);
    }

    await fs.writeFile(filePath, models);

    spinner.succeed(chalk.green.bold('Model structures created'));
  } catch {
    spinner.fail(chalk.red.bold('Model structures creation failed'));
  }
};

export default createModelStructures;
